### PR TITLE
Updated Checks

### PR DESCRIPTION
**Pull request by y011**
SSHD, Screen Sharing and Remote Management checks for both launchd and pids where possible.

Hey these are updated. I manually added your changes (sshdCheck to SSHDCheck etc.) to my fork I think. I will rebase on your merge or I need to work out how to do this right :-)

We should start making a table like this:

| Proc | Checkable by launchctl specifier query | checkable by psutil pid | checkable by pidfile |
| --- | --- | --- | --- |
| sshd / Remote Access | yes for system/com.openssh.sshd | yes (if spawned) | ? |
| Screen Sharing | yes for system/com.apple.screensharing | yes (if spawned) | ? |
| Remote Management / ARDAgent | not that I can see | yes as ARDAgent | ? |
| File Sharing / AppleFIleServer and smbd | not so far - appears to be an launchd XPC service | yes (if spawned) | kdc in /System/Library/ LaunchDaemons/ com.apple.Kerberos.kdc.plist |

In the checks logic I use around launchctl is kinda weird. I'm just testing for its successful execution of a query. It's going to assume that any failure there (like not being able to query launchd for example) means a launchd-spawned service isn't on. Not sure what happens to those if launchd dies. Pretty sure a lot of other stuff will be majorly angry if it does anyway.

Anyway for SSHD I check launchd first and I also check for pids if it's not running from launchd. It will report only one of those conditions with the Sharing one first. 

I think the right way to do this would be to check both, accumulate the results and then return based on that. For that matter I think the pids and launchctl-type checks could be good central functions somewhere since we're just reusing those pretty much the same way in each check at the moment.

### CODE REVIEW

**Comment by snare** [comment]
Hey, rather than adding the changes manually can you please sync your fork per [this document](https://help.github.com/articles/syncing-a-fork/), resolve any merge conflicts generated (where changes weren't copied verbatim) and send a new PR? Otherwise I end up having to resolve merge conflicts every time and history gets messy.

Re: the table, good idea - create a page on the wiki.

Re: `launchctl` checks - yeah once we have them all merged in I'll roll up the common code into some shared classes. I was thinking the same for the "check if process exists" type checks too.

**Comment by snare** [comment]
FYI stuff I changed was mostly to make things more Pythonic. Module names are, by convention, `lowercase_name.py` and class names are `class CamelCaseClassThing(object):`

**Comment by snare** [comment]
Actually don't worry about it, I fixed the merge conflicts this time. But yeah, sync your fork now since I've merged your changes.

**Comment by y011** [comment]
ok i syncd. Changes all cool. Some of the case stuff was aligning with Sharing Pref pane items titles. Screen Sharing, File Sharing etc. 

Something's nqr with screen sharing check. It's alerting when either it or ARD/remote management is on.  It was working right earlier (i swear ;) so I'm not sure what's up. The launchctl thing it's checking for SS seems enabled with either. Will fix

**Comment by snare** [comment]
OK cool. FYI the `if __name__ == "__main__":` stuff in the checks means you can just run them manually from the CLI for testing like this:

```
$ python idiot/checks/apache.py
```

And it'll run the check once and print the result.

**Pull request merged**
